# Nome da Aplicacao
spring.application.name=orbitguardplatform

# Evita erro ao iniciar caso o banco Postgres ainda nao esteja configurado/rodando localmente
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Porta do servidor backend
server.port=8080
